### PR TITLE
Update gh-pages to where master is

### PR DESCRIPTION
**Pull request by jgat**
Kenni, can you maybe also [change the default branch](https://help.github.com/articles/setting-the-default-branch/) to "gh-pages" and delete the master branch?

### CODE REVIEW

**Comment by jgat** [comment]
Added some more data from detective work and memory.

**Comment by kennib** [comment]
This pull request has 24 commits. Lots of them are duplicates. I assume this is because you made a commit a long time ago and it has to also include commits since then (even if I already have them).

Can you do a rebase to make it so the pull request only includes the new commits?

**Comment by jgat** [comment]
Fixed - this pull request is now just fast-forwarding gh-pages to master (a bunch of pre-existing commits).

**Comment by jgat** [comment]
(What I actually would like is for there to be only a gh-pages branch and no master)

**Comment by kennib** [comment]
That sounds like a good idea. Will do.

**Pull request merged**
